spring.application.name=jcode-intelligence

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jcode_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Use Ollama for embeddings
spring.ai.model.embedding=ollama

# Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=gsk_cocklovingfutamaster
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# PgVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Docker
spring.docker.compose.file=jcode-intelligence/compose.yaml